sudo: required
language: node_js
cache:
  directories:
    - node_modules
    - "~/.meteor"
notifications:
  email:
    recipients:
      - "katrotz@gmail.com"
    on_success: always
    on_failure: always
node_js:
  - 4.1
env:
  global:
    - PATH="$HOME/.meteor:$PATH"
before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - "npm install -g spacejam"
script:
  - spacejam test-packages ./
branches:
  only:
    - "master"
services:
  - mongodb
